#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_cms")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_user(tb_user instance);
    partial void Updatetb_user(tb_user instance);
    partial void Deletetb_user(tb_user instance);
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["db_cmsConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_user> tb_users
		{
			get
			{
				return this.GetTable<tb_user>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.chgpwd")]
		public int chgpwd([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string op, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string np)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, op, np);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.delusr")]
		public int delusr([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.findusr")]
		public ISingleResult<findusrResult> findusr([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<findusrResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.frgpwd")]
		public ISingleResult<frgpwdResult> frgpwd([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string mb)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, mb);
			return ((ISingleResult<frgpwdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.logchk")]
		public int logchk([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pwd)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, pwd);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.selectusr")]
		public ISingleResult<selectusrResult> selectusr()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<selectusrResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updusr")]
		public int updusr([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pwd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dob, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string mb, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sts)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name, email, pwd, dob, mb, sts);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.inusr")]
		public int inusr([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pwd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> gen, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dob, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string mb, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sts)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, email, pwd, gen, dob, mb, sts);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_user")]
	public partial class tb_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uid;
		
		private string _uname;
		
		private string _ueml;
		
		private string _upwd;
		
		private System.Nullable<char> _ugen;
		
		private string _udob;
		
		private string _umb;
		
		private System.Nullable<char> _usts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(int value);
    partial void OnuidChanged();
    partial void OnunameChanging(string value);
    partial void OnunameChanged();
    partial void OnuemlChanging(string value);
    partial void OnuemlChanged();
    partial void OnupwdChanging(string value);
    partial void OnupwdChanged();
    partial void OnugenChanging(System.Nullable<char> value);
    partial void OnugenChanged();
    partial void OnudobChanging(string value);
    partial void OnudobChanged();
    partial void OnumbChanging(string value);
    partial void OnumbChanged();
    partial void OnustsChanging(System.Nullable<char> value);
    partial void OnustsChanged();
    #endregion
		
		public tb_user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uname", DbType="VarChar(50)")]
		public string uname
		{
			get
			{
				return this._uname;
			}
			set
			{
				if ((this._uname != value))
				{
					this.OnunameChanging(value);
					this.SendPropertyChanging();
					this._uname = value;
					this.SendPropertyChanged("uname");
					this.OnunameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ueml", DbType="VarChar(50)")]
		public string ueml
		{
			get
			{
				return this._ueml;
			}
			set
			{
				if ((this._ueml != value))
				{
					this.OnuemlChanging(value);
					this.SendPropertyChanging();
					this._ueml = value;
					this.SendPropertyChanged("ueml");
					this.OnuemlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upwd", DbType="VarChar(50)")]
		public string upwd
		{
			get
			{
				return this._upwd;
			}
			set
			{
				if ((this._upwd != value))
				{
					this.OnupwdChanging(value);
					this.SendPropertyChanging();
					this._upwd = value;
					this.SendPropertyChanged("upwd");
					this.OnupwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ugen", DbType="Char(1)")]
		public System.Nullable<char> ugen
		{
			get
			{
				return this._ugen;
			}
			set
			{
				if ((this._ugen != value))
				{
					this.OnugenChanging(value);
					this.SendPropertyChanging();
					this._ugen = value;
					this.SendPropertyChanged("ugen");
					this.OnugenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_udob", DbType="VarChar(50)")]
		public string udob
		{
			get
			{
				return this._udob;
			}
			set
			{
				if ((this._udob != value))
				{
					this.OnudobChanging(value);
					this.SendPropertyChanging();
					this._udob = value;
					this.SendPropertyChanged("udob");
					this.OnudobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_umb", DbType="VarChar(50)")]
		public string umb
		{
			get
			{
				return this._umb;
			}
			set
			{
				if ((this._umb != value))
				{
					this.OnumbChanging(value);
					this.SendPropertyChanging();
					this._umb = value;
					this.SendPropertyChanged("umb");
					this.OnumbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usts", DbType="Char(1)")]
		public System.Nullable<char> usts
		{
			get
			{
				return this._usts;
			}
			set
			{
				if ((this._usts != value))
				{
					this.OnustsChanging(value);
					this.SendPropertyChanging();
					this._usts = value;
					this.SendPropertyChanged("usts");
					this.OnustsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class findusrResult
	{
		
		private int _uid;
		
		private string _uname;
		
		private string _ueml;
		
		private string _upwd;
		
		private System.Nullable<char> _ugen;
		
		private string _udob;
		
		private string _umb;
		
		private System.Nullable<char> _usts;
		
		public findusrResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="Int NOT NULL")]
		public int uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this._uid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uname", DbType="VarChar(50)")]
		public string uname
		{
			get
			{
				return this._uname;
			}
			set
			{
				if ((this._uname != value))
				{
					this._uname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ueml", DbType="VarChar(50)")]
		public string ueml
		{
			get
			{
				return this._ueml;
			}
			set
			{
				if ((this._ueml != value))
				{
					this._ueml = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upwd", DbType="VarChar(50)")]
		public string upwd
		{
			get
			{
				return this._upwd;
			}
			set
			{
				if ((this._upwd != value))
				{
					this._upwd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ugen", DbType="Char(1)")]
		public System.Nullable<char> ugen
		{
			get
			{
				return this._ugen;
			}
			set
			{
				if ((this._ugen != value))
				{
					this._ugen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_udob", DbType="VarChar(50)")]
		public string udob
		{
			get
			{
				return this._udob;
			}
			set
			{
				if ((this._udob != value))
				{
					this._udob = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_umb", DbType="VarChar(50)")]
		public string umb
		{
			get
			{
				return this._umb;
			}
			set
			{
				if ((this._umb != value))
				{
					this._umb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usts", DbType="Char(1)")]
		public System.Nullable<char> usts
		{
			get
			{
				return this._usts;
			}
			set
			{
				if ((this._usts != value))
				{
					this._usts = value;
				}
			}
		}
	}
	
	public partial class frgpwdResult
	{
		
		private string _upwd;
		
		public frgpwdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upwd", DbType="VarChar(50)")]
		public string upwd
		{
			get
			{
				return this._upwd;
			}
			set
			{
				if ((this._upwd != value))
				{
					this._upwd = value;
				}
			}
		}
	}
	
	public partial class selectusrResult
	{
		
		private int _uid;
		
		private string _uname;
		
		private string _ueml;
		
		private string _upwd;
		
		private System.Nullable<char> _ugen;
		
		private string _udob;
		
		private string _umb;
		
		private System.Nullable<char> _usts;
		
		public selectusrResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="Int NOT NULL")]
		public int uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this._uid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uname", DbType="VarChar(50)")]
		public string uname
		{
			get
			{
				return this._uname;
			}
			set
			{
				if ((this._uname != value))
				{
					this._uname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ueml", DbType="VarChar(50)")]
		public string ueml
		{
			get
			{
				return this._ueml;
			}
			set
			{
				if ((this._ueml != value))
				{
					this._ueml = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upwd", DbType="VarChar(50)")]
		public string upwd
		{
			get
			{
				return this._upwd;
			}
			set
			{
				if ((this._upwd != value))
				{
					this._upwd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ugen", DbType="Char(1)")]
		public System.Nullable<char> ugen
		{
			get
			{
				return this._ugen;
			}
			set
			{
				if ((this._ugen != value))
				{
					this._ugen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_udob", DbType="VarChar(50)")]
		public string udob
		{
			get
			{
				return this._udob;
			}
			set
			{
				if ((this._udob != value))
				{
					this._udob = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_umb", DbType="VarChar(50)")]
		public string umb
		{
			get
			{
				return this._umb;
			}
			set
			{
				if ((this._umb != value))
				{
					this._umb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usts", DbType="Char(1)")]
		public System.Nullable<char> usts
		{
			get
			{
				return this._usts;
			}
			set
			{
				if ((this._usts != value))
				{
					this._usts = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
